### ISSUE TITLE
Unable to use two versions of Angular2

### ISSUE THREAD

**Issue by davidgaulin** [joeldenning/simple-single-spa-webpack-example#1]
If I understand properly, based on this setup, since I only have one package.json, I can't run two angular app, running two similar versions of Angular at the same time.  I have dozens of internal Angular app, all maintained separately, all running version of Angular between 2 and 4, that I am trying to show on one screen (not all at the same time) without using Iframes. They are all running on different web server (I will proxy them thru one server), have their own dependencies and framework version, and I would like to keep the ability to be able to deploy them independently. Something this Single-SPA framework can tackle?

**Comment by internettrans** [comment]
The way this example repository is set up, you are right -- it is not set up to use multiple versions of Angular at once. But if you have multiple package.json and webpack.config.js files, then you can do it. You can check out the [single-spa-examples](https://github.com/CanopyTax/single-spa-examples) which demonstrates how to have multiple package.jsons, webpack configs, etc. That repository is much more complicated and might be harder to follow, but it does show how it can be done.

In general, I think it is preferred to have separate package.jsons, webpack configs, and even git repositories for each child application. For simple-single-spa-webpack-example, though, I chose not to do so because I thought it would help keep things easy to understand for people just getting started with single-spa.

Let me know if you get multiple versions of Angular working. If I remember correctly, there is some stuff related to the Angular "platform" concept that might be difficult to reconcile with multiple versions. https://github.com/CanopyTax/single-spa-angular2 tries to solve this, but I'm not sure if it has been tested with two different versions of Angular. So if you'd like to contribute to single-spa-angular2 for that, it would be greatly appreciated.

**Comment by davidgaulin** [comment]
Thanks for the feedback. I will give it a shot and if I can make it work, will contribute back for sure.

**Comment by internettrans** [comment]
@davidgaulin Not sure if this will help you, but I just fixed a somewhat related issue https://github.com/CanopyTax/single-spa-angular2/issues/2 with https://github.com/joeldenning/simple-single-spa-webpack-example/commit/de214097ac93d74f33b21ccaba8ab555873272e1#diff-11e9f7f953edc64ba14b0cc350ae7b9dR9

It is different than your issue here because you're wanting to use multiple versions of angular for separate child applications. If you look at the commit I linked to, it shows how you can have multiple angular apps reusing the same instance of the angular library. I think there's a good case for the shared version of Angular though, since it really helps performance.

**Comment by internettrans** [comment]
Closing for now -- feel free to reopen with further questions or discussion
