### ISSUE TITLE
Do you recommend developing the seperate micro-spas in a monorepo, perhaps lerna?

### ISSUE THREAD

**Issue by factoidforrest** [joeldenning/simple-single-spa-webpack-example#10]
In your webpack example, the apps are all in one repo.  I feel that this would have some benefits for integration.  Lerna could potentially handle library dependency headaches that arise from multiple runtimes all needing to target a new dependency they share.  

Any learnings from you guys on this?

**Comment by internettrans** [comment]
Apologies for the extremely slow response here.

I'm not an expert in Lerna, but my understanding is that it targets publishing multiple npm libraries all at once. With a microservice architecture, I think it's better for different people and teams to own their own git repository, build, and deploy. Lerna is more targeting monorepos and monoliths than microservices.

The reason that all the apps are in the same repo in this example project is simply for convenience and simplicity -- in a larger organization I would recommend the apps being split out into separate git repos and to have their own builds and deploys

Closing this for now since it has been so long since the issue was originally opened, but feel free to reopen with further discussion
