### ISSUE TITLE
webpack.prod.js

### ISSUE THREAD

**Issue by ArtixZ** [joeldenning/simple-single-spa-webpack-example#14]
Thanks for creating this awesome example. 
Just wondering. Do you also have a webpack configuration for production?
Are you able to extract common node modules among these sub-apps?

**Comment by internettrans** [comment]
Hey ArtixZ, sorry for the very slow response. The production webpack config is the same as the development one. The `webpack -p` command [in the build script](https://github.com/joeldenning/simple-single-spa-webpack-example/blob/master/package.json#L7) is what tells webpack to do minification and other production optimizations.

About extracting common node_modules among the sub-apps: since this example is all being done with one webpack config, webpack already only includes one version of shared node_modules. For more information about different build setups, check out https://single-spa.js.org/docs/separating-applications.html
