### ISSUE TITLE
Cannot load App2

### ISSUE THREAD

**Issue by fljmayer** [joeldenning/simple-single-spa-webpack-example#20]
When I click on App2, nothing happens. I see this on the console:
```
single-spa-angular.js:60 Uncaught ReferenceError: props is not defined
    at single-spa-angular.js:60
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)
    at zone.js:889
```

**Comment by internettrans** [comment]
Thanks for reporting this.

You must be using `npm` instead of `yarn`. The bug was not present in single-spa-angular@2.1.0, which is the version used in the yarn.lock. But if you used npm instead, you probably got single-spa-angular@2.2.0 which had a bug.

I have fixed this with [single-spa-angular@2.2.1](https://github.com/CanopyTax/single-spa-angular/releases/tag/v2.2.1) and updated this repo with https://github.com/joeldenning/simple-single-spa-webpack-example/commit/888790b8af87ccdef8839645d3ec630834cb7394.

Do a git pull or re-clone and it should work.
